name: Docker Builder
on:
  pull_request:
    branches:
      - master
    types: ['closed']
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: oracle

      - name: Write .env.properties file
        uses: DamianReeves/write-file-action@v1.3
        with:
          write-mode: overwrite
          contents: |
            spring.datasource.url=${{ secrets.AIVEN_DB_URL }}
            spring.datasource.username=${{ secrets.AIVEN_USERNAME }}
            spring.datasource.password=${{ secrets.AIVEN_PASSWORD }}
          path: src/main/resources/.env.properties

      - name: Build Java Code
        run: gradle bootJar

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: conrad302/inventory-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ env.DOCKER_USER }}
            password: ${{ env.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
